apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: tinahoa5.azurecr.io/book-catalog:1
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: postgresql://project5_lub9_user:etcQySIYY1Wl2eYXTFzOXJX50VV7xrPj@dpg-crmcdaq3esus73fqts5g-a.oregon-postgres.render.com/project5_lub9

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: tinahoa5.azurecr.io/inventory-management:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: postgresql://project5_lub9_user:etcQySIYY1Wl2eYXTFzOXJX50VV7xrPj@dpg-crmcdaq3esus73fqts5g-a.oregon-postgres.render.com/project5_lub9

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8001
